CREATE DATABASE AUTOCAR

USE AUTOCAR

CREATE TABLE AUTOMOVIL
(
Id_Carro INT NOT NULL IDENTITY (1,1)
,Marca VARCHAR(30) NOT NULL
,Modelo VARCHAR(30) NOT NULL
,Pais VARCHAR(50) NOT NULL
,Costo DECIMAL(10,2) NOT NULL
,CONSTRAINT pk_id_carro PRIMARY KEY(Id_Carro)
)

SELECT * FROM AUTOMOVIL

INSERT INTO AUTOMOVIL
(
Marca
,Modelo
,Pais
,Costo
)
VALUES
('Audi', 'A4', 'Alemania',35340000)
,('BMW', 'X6', 'Alemania',55955000)
,('LEXUS', 'UX', 'Japon',43232600)

ALTER TABLE AUTOMOVIL
ALTER COLUMN COSTO DECIMAL(18,2) NOT NULL